info: 
  description: "Training configuration repo"

eureka: 
  client: 
    serviceUrl: 
      defaultZone: https://eureka:eureka@eureka-server-unenfiladed-hedonist.cfapps.io/eureka

--- 

spring: 
 profile: cloud:
 
 eureka:  
      instance:
      hostname: ${vcap.application.uris[0]}
      eureka.instance.nonSecurePort: 80
