info: 
  description: Training configuration repo
  message: A default message given by Application.YML

eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://eureka:eureka@eureka-server-unenfiladed-hedonist.cfapps.io/eureka

--- 

spring:
  profile: cloud
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    eureka.instance.nonSecurePort: 80
