--- 
info: 
  description: "Training configuration repo"
security: 
  user: 
    name: config-server
    password: config-server
spring: 
  cloud: 
    config: 
      server: 
        git: "uri:${vcap.services.config-repo-service.credentials.uri}"